detectors:
  IrresponsibleModule:
    enabled: false
  DataClump:
    enabled: false
  FeatureEnvy:
    exclude:
      - "Virtuous::Client#connection"
      - "Virtuous::Client#unauthorized_connection"
      - "Virtuous::HashHelper#self.deep_transform_keys"
      - "Virtuous::FaradayMiddleware::ParseOj#on_complete"
  NilCheck:
    exclude:
      - "Virtuous::Client#initialize"
  UtilityFunction:
    public_methods_only: true
  NestedIterators:
    exclude:
      - "Virtuous::HashHelper#self.deep_transform_keys"
  TooManyStatements:
    exclude:
      - "Virtuous::HashHelper#self.deep_transform_keys"
      - "Virtuous::Client#connection"
      - "Virtuous::Client#unauthorized_connection"
      - "Virtuous::FaradayMiddleware::VirtuousErrorHandler#on_complete"
  ControlParameter:
    exclude:
      - "Virtuous::Client#initialize"
  NilCheck:
    enabled: false
  TooManyInstanceVariables:
    exclude:
      - "Virtuous::Client"
  InstanceVariableAssumption:
    exclude:
      - "Virtuous::Client"
